#!/bin/env bash

# DESCRIPTION
#   Automate the installation of my environment on supported platforms
#
# TODO(isaacalao):
#   refactor this entire script and use styleguide


# Import isaacalao library
source ./ialib.sh;

# Logs each setup instance 
ialib::loginstance;

# Globals 
ARCH="$(ialib::getarch)";
OSTYPE="$(ialib::getos)";
DISTRO="";

# Functions 
null_bootstrap() {
  ialib::log "Not supported, please use the intended package manager for ${DISTRO}${OSTYPE} [${ARCH}] to install packages." info;
}

osx_bootstrap() {

# TODO(isaacalao):
#     linkconf needs to accomodate more paths

  ialib::linkconf "$(pwd)"/macOS "${HOME}"
  ialib::log;
  ialib::log "Checking if brew is installed." info;

    if ! ialib::log "Homebrew binary path: $(which brew)" info; then

    ialib::log;
    ialib::log \  info;
    ialib::log "If the path is empty it could be a number";
    ialib::log "of things such as a misconfiguration or something";
    ialib::log "of that magnitude, we will assume that";
    ialib::log "it is not installed.";
    ialib::log;

    ialib::log "HOMEBREW IS NOT INSTALLED!" warn;

    if ialib::prompt "Do you want to install it?"; then
      if [[ "$OSTYPE" == "darwin" ]]; then # OSX 10.15 and higher

        ialib::logcmd \
          /bin/bash -c "$(curl -fsSL https://raw.github.com/Homebrew/install/HEAD/install.sh)"
        
        local errno="${?}"
        if [ ${errno} -eq 0 ]; then
          ialib::log "Adding Homebrew to your PATH." info;
          if [ ! "$(grep -c "brew shellenv" "${HOME}/.zshalias")" -eq 1 ]; then
            echo "eval $(/opt/homebrew/bin/brew shellenv)" >> "${HOME}/.zshalias";
            eval "$(/opt/homebrew/bin/brew shellenv)";
          fi
          source "${HOME}/.zshalias";
        else
          ialib::log "Exit code: ${errno}" err
        fi
      fi
    else
      ialib::log "User decided to not install homebrew." warn;
    fi
  else
    ialib::log "HOMEBREW IS ALREADY INSTALLED!" ok;
  fi

# TODO(isaacalao): 
#   Investigate
#     brew bundle with verbose output hangs when installing packages 
#     std::prompt "Do you want to initiate brew bundle (may require sudo)?" && brew -v bundle;
}

ubuntu_bootstrap() {
  null_bootstrap;
}

# Information display
ialib::log \  info;
ialib::log "Architecture: ${ARCH}"; 
ialib::log "Operating System Type: ${OSTYPE}";
ialib::log "Distribution: ${DISTRO}";
ialib::log;

# Bootstrap setup
if [[ "$OSTYPE" = "darwin" ]]; then
  osx_bootstrap;
elif [[ "$OSTYPE" = "linux" ]]; then
  DISTRO="$(grep -w "ID" "/etc/os-release" | tr -d "A-Z=")";
  if [[ "$DISTRO" = "ubuntu" ]]; then
    ubuntu_bootstrap;
  else
    null_bootstrap;
  fi
else
  ialib::log "${OSTYPE} [${ARCH}] is not supported." warn;
fi

# Remove setup log
ialib::prompt "Do you want to remove the log file?" && \
  printf "\x1B[0m\nremoved: %s\n" "$(rm -v "${LOGNAME}")";

# Cleanup
unset OSTYPE ARCH DISTRO && \
unset -f null_bootstrap \
         osx_bootstrap \
         ubuntu_bootstrap;

exit $?; 
