#!/bin/env bash

# DESCRIPTION
#   Automate the installation of my environment on supported platforms
#
# TODO(isaacalao):
#   refactor this entire script and use styleguide


# Import isaacalao library
source ./ialib.sh;

# Logs each setup instance 
ialib::loginstance;

# Globals 
ARCH="$(ialib::getarch)";
OSTYPE="$(ialib::getos)";
DISTRO="$(ialib::getdistro)";

# Functions 
null_bootstrap() {
  ialib::log info;
  ialib::log \ \
    "Not supported, please use the intended package manager for" \
    "${DISTRO}${OSTYPE} [${ARCH}] to install packages.";
}

osx_bootstrap() {

# TODO(isaacalao):
#     linkconf needs to accomodate more paths

  ialib::linkconf "$(pwd)"/macOS "${HOME}"
  ialib::log;
  ialib::log info "Checking if brew is installed.";

    if ! ialib::log info "Homebrew binary path: $(which brew)"; then

      ialib::log info;
      ialib::log \ \
        "If the path is empty it could be a number" \
        "of things such as a misconfiguration or something" \
        "of that magnitude, we will assume that" \
        "it is not installed."
      ialib::log;

      ialib::log warn "HOMEBREW IS NOT INSTALLED!";

      if ialib::prompt "Do you want to install it?"; then
        if [[ "$OSTYPE" == "darwin" ]]; then # OSX 10.15 and higher

          ialib::logcmd \
            /bin/bash -c "$(curl -fsSL https://raw.github.com/Homebrew/install/HEAD/install.sh)"

          if [ ${?} -eq 0 ]; then
            if [ ! "$(grep -c "brew shellenv" "${HOME}/.zshalias")" -eq 1 ]; then
              ialib::log info "Adding Homebrew to your PATH.";
              echo "eval \"\$(/opt/homebrew/bin/brew shellenv)\";" >> "${HOME}/.zshalias";
            else
              ialib::log info "Homebrew is already in your PATH.";
            fi
          else
            ialib::log err "Exit code: ${?}";
            return ${?};
          fi
        fi
    else
      ialib::log warn "User decided to not install homebrew.";
      return $?;
    fi
  else
    ialib::log ok "HOMEBREW IS ALREADY INSTALLED!";
  fi

  if ialib::prompt "Do you want to install packages via Brewfile (may require sudo)?"; then
    eval "$(/opt/homebrew/bin/brew shellenv)";
    ialib::log info "Installing packages via Brewfile.";
    ialib::logcmd cp ./macOS/Brewfile .;
    ialib::logcmd brew bundle install;
    ialib::logcmd rm Brewfile;
  fi
}

ubuntu_bootstrap() {
  null_bootstrap;
}

# Information display
ialib::log info;
ialib::log \ \
  "Architecture: ${ARCH}" \
  "Operating System Type: ${OSTYPE}" \
  "Distribution: ${DISTRO}";
ialib::log;

# Bootstrap setup
if [[ "$OSTYPE" = "darwin" ]]; then
  osx_bootstrap;
elif [[ "$OSTYPE" = "linux" ]]; then
  if [[ "$DISTRO" = "ubuntu" ]]; then
    ubuntu_bootstrap;
  else
    null_bootstrap;
  fi
else
  ialib::log warn "${OSTYPE} [${ARCH}] is not supported.";
fi

# Remove setup log
ialib::prompt "Do you want to remove the log file?" && \
  printf "\x1B[0m\nremoved: %s\n" "$(rm -v "${LOGNAME}")";

# Cleanup
unset OSTYPE ARCH DISTRO && \
unset -f null_bootstrap \
         osx_bootstrap \
         ubuntu_bootstrap;

ialib::prompt "Replace the current running script with ${SHELL}?" && \
  exec "$(which "${SHELL:=NULL}")" || exit ${?};
